name: Lint and test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  lint:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: python -m pip install ruff
      - run: ruff check custom_components tests dev
      - run: ruff format --check custom_components tests dev

  test:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
      - run: python -m pip install -r requirements_test.txt
      - run: pytest tests --cov=custom_components.techem --cov-report=term-missing
